name: Fetch Appstore Info

on:
  workflow_dispatch:
  schedule:
    - cron: "0 * * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2.4.1
        with:
          node-version: "16.x"
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: "true"
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.3"
      - run: gem install bundler
      - run: bundle install
      - run: npm install
      - run: gem install fastlane
      - run: node Sources/check_status.js
        env:
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
          KEY_ID: ${{ secrets.KEY_ID }}
          ISSUER_ID: ${{ secrets.ISSUER_ID }}
          BUNDLE_ID: ${{ secrets.BUNDLE_ID }}
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GIST_ID: ${{ secrets.GIST_ID }}
          
      - run: node Sources/check_status.js for RideMinder
        env:
          PRIVATE_KEY: ${{ secrets.RM_PRIVATE_KEY }}
          KEY_ID: ${{ secrets.RM_KEY_ID }}
          ISSUER_ID: ${{ secrets.RM_ISSUER_ID }}
          BUNDLE_ID: ${{ secrets.RM_BUNDLE_ID }}
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GIST_ID: ${{ secrets.GIST_ID }}

      - run: node Sources/check_status.js for Royale
        env:
          PRIVATE_KEY: ${{ secrets.ROYALE_PRIVATE_KEY }}
          KEY_ID: ${{ secrets.ROYALE_KEY_ID }}
          ISSUER_ID: ${{ secrets.ROYALE_ISSUER_ID }}
          BUNDLE_ID: ${{ secrets.ROYALE_BUNDLE_ID }}
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GIST_ID: ${{ secrets.GIST_ID }}

      - run: node Sources/check_status.js for Encore
        env:
          PRIVATE_KEY: ${{ secrets.ENCORE_PRIVATE_KEY }}
          KEY_ID: ${{ secrets.ENCORE_KEY_ID }}
          ISSUER_ID: ${{ secrets.ENCORE_ISSUER_ID }}
          BUNDLE_ID: ${{ secrets.ENCORE_BUNDLE_ID }}
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GIST_ID: ${{ secrets.GIST_ID }}
